# 運行模式（可選: cook, switch_detect）
mode: cook

# 主程式輪詢頻率（秒）
polling_interval: 2.0

# GPIO 腳位配置（含實體腳位與建議線色）
gpio:
  thermometer_data_pin: 4  # 實體 pin 7：DS18B20 資料腳，固定用 GPIO4（建議線色：藍）
  switch_input_pin: 17     # 實體 pin 11：開關訊號，導通即開（建議線色：灰）
  display_dio_pin: 27      # 實體 pin 13：TM1637 DIO（建議線色：黃）
  display_clk_pin: 22      # 實體 pin 15：TM1637 CLK（建議線色：綠）
  power_led: 10            # 實體 pin 19：電源指示燈（建議線色：棕）
  temp_up_switch_pin: 9    # 實體 pin 21：溫度上調開關（建議線色：橙）
  temp_down_switch_pin: 11 # 實體 pin 23：溫度下調開關（建議線色：紫）

# 電源與接地（實體腳位與建議線色）
# ※ 不參與程式控制，純硬體接線用參考
vcc_pin: 17                # 實體 pin 17：3.3V 電源（建議線色：白）
gnd_pins: 9                # 實體 pin 9：GND（建議線色：黑)

# 顏色layout (實體pin): 藍黑灰黃綠白棕橙紫

# 備註：DS18B20 資料腳與 3.3V 間需串接一顆 4.7kΩ 上拉電阻